### ISSUE TITLE
Bug: Ignores Currency setting and only displays sats

### ISSUE THREAD

**Issue by InsaneSplash** [bitkarrot/free-lnaddress-lnbits#3]
- When setting a currency, lnaddy ignores the currency and shows all values in sats.
- Each value displayed in the invoice is 1000 less than the value configured within the extension. (0.001)
-- 100 sats is shown as 1 sat, 10 sats is shown as 1 sat, 1001 sats are shown as 2 sats (rounded up)

**Comment by bitkarrot** [comment]
It looks like it also happens on the lnurlp extension, yes? If so then we should make this an issue on the main lnbits repo.

**Comment by InsaneSplash** [comment]
The number value configured now shows correctly, however its not converting the value to a currency if defined.

i.e. 3001 ZAR is shown as 3001 sats (ZAR 8.40)

**Comment by bitkarrot** [comment]
Does this issue also happen on lnurlp extension?

**Comment by InsaneSplash** [comment]
Testing shows its converting correctly now.
