### ISSUE TITLE
Bug: QR Code Error

### ISSUE THREAD

**Issue by InsaneSplash** [bitkarrot/free-lnaddress-lnbits#4]
When displaying the QR code linked to the LN Address, scanning this QR code produces an error.

`Bad response from server`

It tries to access the URL : `/lnurlp/api/v1/lnurl/<id>`

**Comment by bitkarrot** [comment]
Fixed on branch of main repo at https://github.com/bitkarrot/lnbits-legend/tree/free-lnaddress

due to differences in repo, will push here tomorrow

Thanks so much @InsaneSplash for testing and reporting!

**Comment by bitkarrot** [comment]
Ok I pushed to this branch, its a copy from the other tree. If there are conflicts with old versions let me know, a lot has changed

**Comment by InsaneSplash** [comment]
This seems to work now, and is showing the Currency vs Sats conversion.

Setting say 3001 on the currency, when scanned shows 2900.01

**Comment by InsaneSplash** [comment]
When setting to sats, it shows correctly.

**Comment by InsaneSplash** [comment]
Note: when trying to pay the invoice, I recieve an alert back ` Invoice description_hash doesn't match metadata.`

I use the QR code from the Lightning Address and I genberated my own using a QR Generator. Both scan and produce the invoice, but trying to pay, produces the error.

**Comment by bitkarrot** [comment]
also see https://github.com/lnbits/lnbits/issues/1224

**Comment by bitkarrot** [comment]
@InsaneSplash Also please let me know what is the current commit number for the deploy you are testing on, or better yet, just share with me your fork on github that you're using. 

This will help a lot due to the massive # of recent (and ongoing changes). Thanks!

**Comment by InsaneSplash** [comment]
> Note: when trying to pay the invoice, I recieve an alert back  Invoice description_hash doesn't match metadata.



I have installed the latest main branch from LNBITS and your port.

I am still getting the error when trying to settle the invoice.

**Comment by bitkarrot** [comment]
> Note: when trying to pay the invoice, I recieve an alert back ` Invoice description_hash doesn't match metadata.`
> 
> I use the QR code from the Lightning Address and I genberated my own using a QR Generator. Both scan and produce the invoice, but trying to pay, produces the error.

Could you please tell me what wallet you are using when getting this error? 

also does the error happen when visiting the lightning address from sendsats.to? I am noticing discrepancies between wallets and how they resolve lightning addresses. thanks

**Comment by InsaneSplash** [comment]
I am using a wallet from LNBits and when I try to use the sendsats.to site I get this error.

`[{"msg":"Not a valid Lightning Address. Sorry!"}]`

**Comment by bitkarrot** [comment]
> I am using a wallet from LNBits and when I try to use the sendsats.to site I get this error.
> 
> `[{"msg":"Not a valid Lightning Address. Sorry!"}]`

Thanks. I think i finally found the source of the error. Will need to fix formatting issues on the branch then resubmit it. 

again thanks for your help testing.

**Comment by bitkarrot** [comment]
leaving reference to description hash check here: https://github.com/getAlby/lightning-browser-extension/pull/735

**Comment by bitkarrot** [comment]
Closing this issue
