### ISSUE TITLE
Bug: invalid description_hash

### ISSUE THREAD

**Issue by daywalker90** [bitkarrot/free-lnaddress-lnbits#6]
Hi, trying out the extension and for now i only got it working in combination with sendsats.to.
In ZBD i get a invalid description_hash error. Expected 3fd78... got 8c020.... 
I checked my node and the invoice had indeed 8c020... as description_hash.
Same with blue wallet i get a `invoice description_hash doesn't match metadata` error
cln: 22.11.1
lnbits [823956395b8e3d9c912f3307eb2ce3bfb1606b00](https://github.com/lnbits/lnbits/commit/823956395b8e3d9c912f3307eb2ce3bfb1606b00)

when browsing to https://mydomain.com/.well-known/lnurlp/daywalker i get this: 
`{"tag":"payRequest","callback":"https://mydomain.com/lnaddy/api/v1/lnurl/cb/1","metadata":"[[\"text/plain\", \"Payment to daywalker\"], [\"text/identifier\", \"daywalker@mydomain.com\"]]","minSendable":1000,"maxSendable":100000}`

**Comment by bitkarrot** [comment]
Ah i just realized this repo is not up to date like this one is  over at the lnbits, see if this makes a difference

https://github.com/lnbits/free-lnaddress-extension/

eventually i'll need to merge in the differences, but fore now see it the other one is working. you'll see need to keep the changes to core lnbits/core/views/public_api.py

**Comment by daywalker90** [comment]
i got an error when visiting the extension tab after switching the repo and my ln-address was missing, so i switched back and deleted it. Now back again to the new one, error message is gone and i want to recreate the address again i get this error: (the one on the website disappears too fast so this is from the log)
```
Feb 18 02:25:45 poetry[1767065]: 2023-02-18 02:25:45.00 | ERROR | Exception in ASGI application
Feb 18 02:25:45 poetry[1767065]: ERROR:uvicorn.error:Exception in ASGI application
Feb 18 02:25:45 poetry[1767065]: psycopg2.errors.UndefinedColumn: column "wallet_key" of relation "pay_links" does not exist
Feb 18 02:25:45 poetry[1767065]: LINE 4:             wallet_key,
Feb 18 02:25:45 poetry[1767065]:                     ^
Feb 18 02:25:45 poetry[1767065]: The above exception was the direct cause of the following exception:
Feb 18 02:25:45 poetry[1767065]: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "wallet_key" of relation "pay_links" does not exist
Feb 18 02:25:45 poetry[1767065]: LINE 4:             wallet_key,
Feb 18 02:25:45 poetry[1767065]:                     ^
Feb 18 02:25:45 poetry[1767065]: [SQL:
Feb 18 02:25:45 poetry[1767065]:         INSERT INTO lnaddy.pay_links (
Feb 18 02:25:45 poetry[1767065]:             wallet,
Feb 18 02:25:45 poetry[1767065]:             wallet_key,
Feb 18 02:25:45 poetry[1767065]:             description,
Feb 18 02:25:45 poetry[1767065]:             min,
Feb 18 02:25:45 poetry[1767065]:             max,
Feb 18 02:25:45 poetry[1767065]:             served_meta,
Feb 18 02:25:45 poetry[1767065]:             served_pr,
Feb 18 02:25:45 poetry[1767065]:             webhook_url,
Feb 18 02:25:45 poetry[1767065]:             webhook_headers,
Feb 18 02:25:45 poetry[1767065]:             webhook_body,
Feb 18 02:25:45 poetry[1767065]:             success_text,
Feb 18 02:25:45 poetry[1767065]:             success_url,
Feb 18 02:25:45 poetry[1767065]:             comment_chars,
Feb 18 02:25:45 poetry[1767065]:             currency,
Feb 18 02:25:45 poetry[1767065]:             fiat_base_multiplier,
Feb 18 02:25:45 poetry[1767065]:             lnaddress
Feb 18 02:25:45 poetry[1767065]:         )
Feb 18 02:25:45 poetry[1767065]:         VALUES (%s, %s, %s, %s, %s, 0, 0, %s, %s, %s, %s, %s, %s, %s, %s, %s)
Feb 18 02:25:45 poetry[1767065]:         RETURNING ID
Feb 18 02:25:45 poetry[1767065]:         ]
Feb 18 02:25:45 poetry[1767065]: [parameters: ('0b4f638b1d724d25b9125fd3bb5e3d2f', '399e45fedeab44e7b387eefd40f73488', 'SATS', 10.0, 100000000.0, None, None, None, None, None, 250, None, 100, 'daywalker')]
Feb 18 02:25:45 poetry[1767065]: (Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by bitkarrot** [comment]
mm looks like you have to redo the database table initiation as they are different. maybe drop the lnaddy table and retry?

i'm pretty sure the extension under the lnbits repo is working, as we cross checked it before pushing it there a few weeks ago.  sorry for the confusion lots of stuff changing and breaking

**Comment by daywalker90** [comment]
no problem, dropped the table, fixed the problem, had to change lnurl_response to lnaddy_lnurl_response in the public_api but now i get this in lnbits logs when trying a payment:
```
Feb 18 04:30:32 poetry[1787422]: 2023-02-18 04:30:32.71 | ERROR | HTTPException 520: 'description_hash' unsupported by CLN, provide 'unhashed_description'
Feb 18 04:30:32 poetry[1787422]: 2023-02-18 04:30:32.71 | INFO | 2a02:8108:8ac0:207b:d250:99ff:fe9e:792a:0 - "POST /api/v1/payments HTTP/1.1" 520
Feb 18 04:30:32 poetry[1787422]: KeyError: 'payment_request'
Feb 18 04:30:32 poetry[1787422]: 2023-02-18 04:30:32.73 | ERROR | Exception: 'payment_request'
Feb 18 04:30:32 poetry[1787422]: 2023-02-18 04:30:32.73 | INFO | 54.173.212.127:0 - "GET /lnaddy/api/v1/lnurl/cb/1?amount=10000&nonce=1676691031762 HTTP/1.1" 500
Feb 18 04:30:32 poetry[1787422]: 2023-02-18 04:30:32.74 | ERROR | Exception in ASGI application
Feb 18 04:30:32 poetry[1787422]: ERROR:uvicorn.error:Exception in ASGI application
Feb 18 04:30:32 poetry[1787422]: KeyError: 'payment_request'
```

**Comment by bitkarrot** [comment]
> ERROR | HTTPException 520: 'description_hash' unsupported by CLN, provide 'unhashed_description'

Well that's odd, I wonder if this is a CLN issue?

**Comment by daywalker90** [comment]
depends how you define issue. cln only has a flag for it to return a description_hash instead of the description when creating an invoice via rpc: https://lightning.readthedocs.io/lightning-invoice.7.html and the unhashed description needs to be communicated by something else. Maybe compare with lnurlp's function?:  https://github.com/lnbits/lnurlp/blob/main/lnurl.py#L52

**Comment by daywalker90** [comment]
i got it working for me in https://github.com/lnbits/free-lnaddress-extension/pull/2 but i have no idea what im actually doing so please review carefully :)
